Todo List
NuffSaid-Bore/Todo-List pull request #2
Opened 2024-11-12 10:48 UTC by NuffSaid-Bore

Todo List with JavaScript and Online Database MongoDB Atlas that basically uses CRUD Operations

2024-11-12 11:05 UTC, NuffSaid-Bore commented
@Sinawo, @BAHLEMAJOLA, @zolwethu, @TshepoMagagula This is how my project currently looks like

![Screenshot 2024-11-12 130426](https://github.com/user-attachments/assets/b3b800aa-24aa-4176-8ac8-0ee7ab8be649)
![Screenshot 2024-11-12 130505](https://github.com/user-attachments/assets/56d9d075-7a63-48e5-88f7-9ea6a4711d8d)
I look forward to your reviews

2024-11-13 09:24 UTC, zolwethu requested changes
move the "incomplete" and "compete" up a notch, so they are in the same card as the "To Do List" header/title

2024-11-13 09:44 UTC, BAHLEMAJOLA commented on Frontend/src/components/NoteModal.jsx
> +            const response = await axios.post("http://localhost:5000/add",
@NuffSaid-Bore please display a user-friendly error message on the modal if the request fails.
for example; catch (error) {
        setError('Failed to add the task. Please try again .');
        console.log(error);

2024-11-13 10:04 UTC, BAHLEMAJOLA requested changes
@NuffSaid-Bore please display a user-friendly error message on the modal if the request fails.
for example; catch (error) {
setError('Failed to add the task. Please try again .');
console.log(error);

2024-11-13 10:07 UTC, NuffSaid-Bore commented
> @NuffSaid-Bore please move the "incomplete" and "compete" buttons up a notch, so they are in the same card as the "To Do List" header/title

@zolwethu Thanks for your review, this is the intended design, Please elaborate request for change in the Frontend perspective

2024-11-13 10:09 UTC, NuffSaid-Bore commented
> @NuffSaid-Bore please display a user-friendly error message on the modal if the request fails. for example; catch (error) { setError('Failed to add the task. Please try again .'); console.log(error);

@BAHLEMAJOLA I appreciate the review, please find attached screenshot for your requested changes. I already included the error and success validations.
![Screenshot 2024-11-13 120147](https://github.com/user-attachments/assets/c161cb49-d8fe-4edd-a600-d1ed7c60f6c6)

2024-11-14 07:17 UTC, TshepoMagagula reviewed
@NuffSaid-Bore I'm happy with the project, it is responsive and the README is comprehensive, I give you a go ahead to merge the pull request

2024-11-14 07:50 UTC, NuffSaid-Bore commented
> @NuffSaid-Bore I'm happy with the project, it is responsive and the README is comprehensive, I give you a go ahead to merge the pull request

@TshepoMagagula The review is much appreciated! awaiting other team members for their go ahead.

2024-11-15 06:17 UTC, BAHLEMAJOLA approved these changes
Great you can now merge 💯

2024-11-15 06:31 UTC, zolwethu commented
> > @NuffSaid-Bore please move the "incomplete" and "compete" buttons up a notch, so they are in the same card as the "To Do List" header/title
> 
> @zolwethu Thanks for your review, this is the intended design, Please elaborate request for change in the Frontend perspective

@NuffSaid-Bore Alright, but at least move the Title "To Do List" to the middle of the card

2024-11-15 07:25 UTC, NuffSaid-Bore commented
> > > @NuffSaid-Bore please move the "incomplete" and "compete" buttons up a notch, so they are in the same card as the "To Do List" header/title
> > 
> > 
> > @zolwethu Thanks for your review, this is the intended design, Please elaborate request for change in the Frontend perspective
> 
> @NuffSaid-Bore Alright, but at least move the Title "To Do List" to the middle of the card

@zolwethu I have intergrated the requested changes.

2024-11-15 07:28 UTC, zolwethu approved these changes
Title should almost always be centered, looks goodnow

2024-11-15 12:37 UTC, merged